name: Run Tests

on:
  pull_request:
    branches: ['master']

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # More reliable OpenJDK distribution
          java-version: '8'

      - name: Build and Test with Maven
        run: mvn clean verify
